apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price
  template:
    metadata:
      labels:
        app: house-price
    spec:
      containers:
      - name: house-price-container
        image: your-dockerhub-username/house-price-ml:latest
        ports:
        - containerPort: 8080